import sample from '@/assets/img/sample.png';

export const mockBooks = [
  {
    rank: 1,
    title: '단 한 번의 삶',
    author: '김영하',
    publisher: '복복서가',
    discountRate: 10,
    price: 15120,
    point: 840,
    rating: 4,
    review: '감동이에요',
    deliveryDate: '오늘(4/24, 목)',
    isLiked: false,
    imageUrl: sample,
  },
  {
    rank: 2,
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    discountRate: 15,
    price: 13500,
    point: 700,
    rating: 4,
    review: '재밌어요',
    deliveryDate: '오늘(4/24, 목)',
    isLiked: true,
    imageUrl: sample,
  },
  {
    rank: 3,
    title: '모순',
    author: '양귀자',
    publisher: '쓰다',
    discountRate: 5,
    price: 12420,
    point: 620,
    rating: 5,
    review: '여운이 길어요',
    deliveryDate: '오늘(5/20, 월)',
    isLiked: false,
    imageUrl: sample,
  },
  {
    rank: 4,
    title: '책은 도끼다',
    author: '박웅현',
    publisher: '북하우스',
    discountRate: 12,
    price: 14200,
    point: 750,
    rating: 3,
    review: '생각하게 만드는 책',
    deliveryDate: '오늘(5/20, 월)',
    isLiked: true,
    imageUrl: sample,
  },
  {
    rank: 5,
    title: '아몬드',
    author: '손원평',
    publisher: '창비',
    discountRate: 10,
    price: 11700,
    point: 610,
    rating: 1,
    review: '몰입감 최고',
    deliveryDate: '오늘(5/20, 월)',
    isLiked: true,
    imageUrl: sample,
  },
];