import sample from '@/assets/img/sample.png';

export const mockBooks = [
  {
    id: 1,
    title: '단 한 번의 삶',
    author: '김영하',
    publisher: '복복서가',
    price: 15120,
    rank: 1,
    imageUrl: sample,
    star: 4,
    bestEmotion: '감동이에요',
  },
  {
    id: 2,
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    price: 13500,
    rank: 2,
    imageUrl: sample,
    star: 4,
    bestEmotion: '재밌어요',
  },
  {
    id: 3,
    title: '모순',
    author: '양귀자',
    publisher: '쓰다',
    price: 12420,
    rank: 3,
    imageUrl: sample,
    star: 5,
    bestEmotion: '여운이 길어요',
  },
  {
    id: 4,
    title: '책은 도끼다',
    price: 14200,
    author: '박웅현',
    publisher: '북하우스',
    rank: 4,
    imageUrl: sample,
    star: 3,
    bestEmotion: '생각하게 만드는 책',
  },
  {
    id: 5,
    title: '아몬드',
    price: 11700,
    author: '손원평',
    publisher: '창비',
    rank: 5,
    imageUrl: sample,
    star: 1,
    bestEmotion: '몰입감 최고',
  },
];
